### ISSUE TITLE
query-params are not preserved

### ISSUE THREAD

**Issue by aaronblenkush** [GentlemanHal/ring-curl#3]
The helper function `ring-curl.clj-http/convert` does not preserve `:query-params`. This is not necessarily an issue with the core library because the user can always choose their own middleware when converting from a clj-http request to a ring request. However, it might be good to fix this for general use cases.

It looks like within the `ring-curl.clj-http` namespace moving `wrap-query-params` to the end of the `middleware` vector fixes the issue. This is because `wrap-url` will wipe out the `:query-string` if the `:url` doesn't contain a query string segment.

See the following snippet for an example. We expect `http://localhost/test?k=v`, but we get `http://localhost/test`.

    (ns llama.tmp
      (:require [ring-curl.clj-http]
                [ring-curl.core]
                [clj-http.client]))
   
    (ring-curl.core/to-curl
      (ring-curl.clj-http/convert
        {:url          "http://localhost/test"
         :query-params {"k" "v"}}))
    ;; => curl -v -X GET "http://localhost/test"

Can be fixed by using the following `ring-curl.clj-http/middleware`:

    (def middleware
      [wrap-basic-auth
       wrap-oauth
       wrap-user-info
       wrap-url
       wrap-accept
       wrap-accept-encoding
       wrap-content-type
       wrap-form-params
       wrap-nested-params
       wrap-method
       wrap-query-params])

**Comment by GentlemanHal** [comment]
@aaronblenkush thanks for submitting this bug!

I've fixed the code and pushed a new version to clojars 😄

**Comment by GentlemanHal** [comment]
I'm pretty sure the version pushed to clojars is broken 😭

More details in issue #4
